# Generated by Django 2.1.5 on 2020-07-14 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commonObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locationType', models.CharField(max_length=50, verbose_name='Location Type')),
                ('location', models.CharField(max_length=50)),
                ('dateLastModified', models.DateTimeField(default='2000-1-1', max_length=50, verbose_name='Date Last Modified')),
                ('lastUpdatedUser', models.CharField(max_length=50, verbose_name='Last Updated User')),
                ('Notes', models.CharField(max_length=100)),
                ('modelName', models.CharField(max_length=50, verbose_name='Model Name')),
                ('token', models.CharField(default=0, max_length=30)),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DataCenterEquipment',
            fields=[
                ('commonobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.commonObject')),
                ('macAddress', models.CharField(max_length=50, verbose_name='Mac Address')),
                ('Type', models.CharField(max_length=50)),
                ('serialNumber', models.CharField(max_length=50, verbose_name='Serial Number')),
                ('assetTag', models.CharField(max_length=50, verbose_name='Asset Tag')),
            ],
            bases=('inventory.commonobject',),
        ),
        migrations.CreateModel(
            name='Desktops',
            fields=[
                ('commonobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.commonObject')),
                ('user', models.CharField(max_length=50)),
                ('serialNumber', models.CharField(max_length=50, verbose_name='Serial Number')),
                ('macAddress', models.CharField(max_length=50, verbose_name='Mac Address')),
                ('IPAddress', models.CharField(max_length=50, verbose_name='IP Address')),
                ('OS', models.CharField(max_length=50, verbose_name='OS Type')),
                ('userType', models.CharField(max_length=50, verbose_name='User Type')),
            ],
            bases=('inventory.commonobject',),
        ),
        migrations.CreateModel(
            name='DesktopScanners',
            fields=[
                ('commonobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.commonObject')),
                ('serialNumber', models.CharField(max_length=50, verbose_name='Serial Number')),
            ],
            bases=('inventory.commonobject',),
        ),
        migrations.CreateModel(
            name='Notebooks',
            fields=[
                ('commonobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.commonObject')),
                ('user', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('modelNumber', models.CharField(max_length=50, verbose_name='Model Number')),
                ('OS', models.CharField(max_length=50, verbose_name='OS Type')),
                ('serialNumber', models.CharField(max_length=50, verbose_name='Serial Number')),
                ('manufacturedYear', models.CharField(max_length=50, verbose_name='Manufactured Year')),
                ('size', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('userType', models.CharField(max_length=50, verbose_name='User Type')),
            ],
            bases=('inventory.commonobject',),
        ),
        migrations.CreateModel(
            name='Peripherals',
            fields=[
                ('commonobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.commonObject')),
                ('user', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('givenDate', models.CharField(max_length=50, verbose_name='Given Date')),
            ],
            bases=('inventory.commonobject',),
        ),
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('commonobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.commonObject')),
                ('user', models.CharField(max_length=50)),
                ('cartridgeType', models.CharField(max_length=50, verbose_name='Cartridge Type')),
                ('macAddress', models.CharField(max_length=50, verbose_name='Mac Address')),
                ('givenDate', models.CharField(max_length=50, verbose_name='Given Date')),
                ('serialNumber', models.CharField(max_length=50, verbose_name='Serial Number')),
            ],
            bases=('inventory.commonobject',),
        ),
        migrations.CreateModel(
            name='StationaryProjectors',
            fields=[
                ('commonobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.commonObject')),
                ('bulb', models.CharField(max_length=50)),
            ],
            bases=('inventory.commonobject',),
        ),
    ]
