# Generated by Django 2.1.5 on 2020-06-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataCenterEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationType', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('macAddress', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('serialNumber', models.CharField(max_length=50)),
                ('assetTag', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=400)),
                ('lastUpdatedUser', models.CharField(max_length=50)),
                ('dateLastModified', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Desktops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
                ('modelName', models.CharField(max_length=50)),
                ('locationType', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('dateLastModified', models.DateTimeField(editable=False)),
                ('serialNumber', models.CharField(max_length=50)),
                ('macAddress', models.CharField(max_length=50)),
                ('IPAddress', models.CharField(max_length=50)),
                ('OS', models.CharField(max_length=50)),
                ('userType', models.CharField(max_length=50)),
                ('Notes', models.CharField(max_length=50)),
                ('lastUpdatedUser', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='desktopScanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationType', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('modelName', models.CharField(max_length=50)),
                ('serialNumber', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=400)),
                ('lastUpdatedUser', models.CharField(max_length=50)),
                ('dateLastModified', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notebooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationType', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('modelNumber', models.CharField(max_length=50)),
                ('OS', models.CharField(max_length=50)),
                ('serialNumber', models.CharField(max_length=50)),
                ('manufacturedYear', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('givenTo', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('userType', models.CharField(max_length=50)),
                ('dateLastModified', models.DateTimeField(editable=False)),
                ('lastUpdatedUser', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Peripherals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationType', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('givenTo', models.CharField(max_length=50)),
                ('givenDate', models.CharField(max_length=50)),
                ('dateLastModified', models.DateTimeField(editable=False)),
                ('lastUpdatedUser', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modelName', models.CharField(max_length=50)),
                ('locationType', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('cartridgeType', models.CharField(max_length=50)),
                ('macAddress', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('givenDate', models.CharField(max_length=50)),
                ('dateLastModified', models.DateTimeField(editable=False)),
                ('lastUpdatedUser', models.CharField(max_length=50)),
                ('serialNumber', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='stationaryProjectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationType', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('modelName', models.CharField(max_length=50)),
                ('bulb', models.CharField(max_length=50)),
                ('lastUpdatedUser', models.CharField(max_length=50)),
                ('dateLastModified', models.CharField(max_length=50)),
            ],
        ),
    ]
