# Generated by Django 2.1.5 on 2020-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenterequipment',
            name='token',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='desktops',
            name='token',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='desktopscanners',
            name='token',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='notebooks',
            name='token',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='peripherals',
            name='token',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='printers',
            name='token',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='stationaryprojectors',
            name='token',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='datacenterequipment',
            name='assetTag',
            field=models.CharField(max_length=50, verbose_name='Asset Tag'),
        ),
        migrations.AlterField(
            model_name='datacenterequipment',
            name='dateLastModified',
            field=models.DateTimeField(max_length=50, verbose_name='Date Last Modified'),
        ),
        migrations.AlterField(
            model_name='datacenterequipment',
            name='lastUpdatedUser',
            field=models.CharField(max_length=50, verbose_name='Last Updated User'),
        ),
        migrations.AlterField(
            model_name='datacenterequipment',
            name='locationType',
            field=models.CharField(max_length=50, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='datacenterequipment',
            name='macAddress',
            field=models.CharField(max_length=50, verbose_name='Mac Address'),
        ),
        migrations.AlterField(
            model_name='datacenterequipment',
            name='modelName',
            field=models.CharField(max_length=50, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='datacenterequipment',
            name='serialNumber',
            field=models.CharField(max_length=50, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='IPAddress',
            field=models.CharField(max_length=50, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='OS',
            field=models.CharField(max_length=50, verbose_name='OS Type'),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='dateLastModified',
            field=models.DateTimeField(max_length=50, verbose_name='Date Last Modified'),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='lastUpdatedUser',
            field=models.CharField(max_length=50, verbose_name='Last Updated User'),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='locationType',
            field=models.CharField(max_length=50, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='macAddress',
            field=models.CharField(max_length=50, verbose_name='Mac Address'),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='modelName',
            field=models.CharField(max_length=50, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='serialNumber',
            field=models.CharField(max_length=50, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='userType',
            field=models.CharField(max_length=50, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='desktopscanners',
            name='dateLastModified',
            field=models.DateTimeField(max_length=50, verbose_name='Date Last Modified'),
        ),
        migrations.AlterField(
            model_name='desktopscanners',
            name='lastUpdatedUser',
            field=models.CharField(max_length=50, verbose_name='Last Updated User'),
        ),
        migrations.AlterField(
            model_name='desktopscanners',
            name='locationType',
            field=models.CharField(max_length=50, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='desktopscanners',
            name='modelName',
            field=models.CharField(max_length=50, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='desktopscanners',
            name='serialNumber',
            field=models.CharField(max_length=50, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='OS',
            field=models.CharField(max_length=50, verbose_name='OS Type'),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='dateLastModified',
            field=models.DateTimeField(max_length=50, verbose_name='Date Last Modified'),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='lastUpdatedUser',
            field=models.CharField(max_length=50, verbose_name='Last Updated User'),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='locationType',
            field=models.CharField(max_length=50, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='manufacturedYear',
            field=models.CharField(max_length=50, verbose_name='Manufactured Year'),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='modelName',
            field=models.CharField(max_length=50, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='modelNumber',
            field=models.CharField(max_length=50, verbose_name='Model Number'),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='serialNumber',
            field=models.CharField(max_length=50, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='userType',
            field=models.CharField(max_length=50, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='peripherals',
            name='dateLastModified',
            field=models.DateTimeField(max_length=50, verbose_name='Date Last Modified'),
        ),
        migrations.AlterField(
            model_name='peripherals',
            name='givenDate',
            field=models.CharField(max_length=50, verbose_name='Given Date'),
        ),
        migrations.AlterField(
            model_name='peripherals',
            name='lastUpdatedUser',
            field=models.CharField(max_length=50, verbose_name='Last Updated User'),
        ),
        migrations.AlterField(
            model_name='peripherals',
            name='locationType',
            field=models.CharField(max_length=50, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='peripherals',
            name='modelName',
            field=models.CharField(max_length=50, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='cartridgeType',
            field=models.CharField(max_length=50, verbose_name='Cartridge Type'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='dateLastModified',
            field=models.DateTimeField(max_length=50, verbose_name='Date Last Modified'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='givenDate',
            field=models.CharField(max_length=50, verbose_name='Given Date'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='lastUpdatedUser',
            field=models.CharField(max_length=50, verbose_name='Last Updated User'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='locationType',
            field=models.CharField(max_length=50, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='macAddress',
            field=models.CharField(max_length=50, verbose_name='Mac Address'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='modelName',
            field=models.CharField(max_length=50, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='serialNumber',
            field=models.CharField(max_length=50, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='stationaryprojectors',
            name='dateLastModified',
            field=models.DateTimeField(max_length=50, verbose_name='Date Last Modified'),
        ),
        migrations.AlterField(
            model_name='stationaryprojectors',
            name='lastUpdatedUser',
            field=models.CharField(max_length=50, verbose_name='Last Updated User'),
        ),
        migrations.AlterField(
            model_name='stationaryprojectors',
            name='locationType',
            field=models.CharField(max_length=50, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='stationaryprojectors',
            name='modelName',
            field=models.CharField(max_length=50, verbose_name='Model Name'),
        ),
    ]
