# Generated by Django 2.1.5 on 2020-07-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonobject',
            name='lastUpdatedUser',
            field=models.CharField(default='', max_length=50, verbose_name='Last Updated User'),
        ),
        migrations.AlterField(
            model_name='commonobject',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='commonobject',
            name='locationType',
            field=models.CharField(default='', max_length=50, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='commonobject',
            name='modelName',
            field=models.CharField(default='', max_length=50, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='commonobject',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='IPAddress',
            field=models.CharField(default='', max_length=50, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='OS',
            field=models.CharField(default='', max_length=50, verbose_name='OS Type'),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='macAddress',
            field=models.CharField(default='', max_length=50, verbose_name='Mac Address'),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='serialNumber',
            field=models.CharField(default='', max_length=50, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='userType',
            field=models.CharField(default='', max_length=50, verbose_name='User Type'),
        ),
    ]
