# Generated by Django 2.1.5 on 2020-07-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200706_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonobject',
            name='dateLastModified',
            field=models.DateTimeField(default='2000-1-1', max_length=50, verbose_name='Date Last Modified'),
        ),
    ]
