# Generated by Django 2.1.5 on 2020-07-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200714_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenterequipment',
            name='Type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='datacenterequipment',
            name='assetTag',
            field=models.CharField(default='', max_length=50, verbose_name='Asset Tag'),
        ),
        migrations.AlterField(
            model_name='datacenterequipment',
            name='macAddress',
            field=models.CharField(default='', max_length=50, verbose_name='Mac Address'),
        ),
        migrations.AlterField(
            model_name='datacenterequipment',
            name='serialNumber',
            field=models.CharField(default='', max_length=50, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='desktopscanners',
            name='serialNumber',
            field=models.CharField(default='', max_length=50, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='manufacturedYear',
            field=models.CharField(default='', max_length=50, verbose_name='Manufactured Year'),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='modelNumber',
            field=models.CharField(default='', max_length=50, verbose_name='Model Number'),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='purpose',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='serialNumber',
            field=models.CharField(default='', max_length=50, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='userType',
            field=models.CharField(default='', max_length=50, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='peripherals',
            name='givenDate',
            field=models.DateTimeField(default='2000-1-1', max_length=50, verbose_name='Given Date'),
        ),
        migrations.AlterField(
            model_name='peripherals',
            name='make',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='peripherals',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='printers',
            name='cartridgeType',
            field=models.CharField(default='', max_length=50, verbose_name='Cartridge Type'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='givenDate',
            field=models.DateTimeField(default='2000-1-1', max_length=50, verbose_name='Given Date'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='macAddress',
            field=models.CharField(default='', max_length=50, verbose_name='Mac Address'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='serialNumber',
            field=models.CharField(default='', max_length=50, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
