# Generated by Django 2.1.5 on 2020-07-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200706_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacenterequipment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='desktops',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='desktopscanners',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='notebooks',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='peripherals',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='printers',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='stationaryprojectors',
            name='slug',
        ),
        migrations.AddField(
            model_name='commonobject',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
