# Generated by Django 2.1.5 on 2020-07-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200720_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktops',
            old_name='IPAddress',
            new_name='IpAddress',
        ),
    ]
