# Generated by Django 2.1.5 on 2020-07-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200721_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonobject',
            name='locationType',
        ),
        migrations.AddField(
            model_name='commonobject',
            name='building',
            field=models.CharField(choices=[('WWH', 'WWH'), ('60FifthAve', '60FifthAve'), ('Other', 'Other')], default='WWH', max_length=50, verbose_name='Building'),
        ),
    ]
