# Generated by Django 2.1.5 on 2020-07-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200724_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonobject',
            name='qrcode',
            field=models.CharField(default='http://google.com', max_length=100),
        ),
    ]
