# Generated by Django 2.1.5 on 2020-08-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200731_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonobject',
            name='slug',
            field=models.SlugField(default='', max_length=256),
        ),
    ]
