# Generated by Django 2.1.5 on 2020-08-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_macs_givendate'),
    ]

    operations = [
        migrations.AddField(
            model_name='macs',
            name='appleCareExpirationDate',
            field=models.CharField(default='', max_length=50, verbose_name='AppleCare Expiration Date'),
        ),
    ]
