# Generated by Django 2.1.5 on 2020-08-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20200811_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printercartridges',
            fields=[
                ('commonobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.commonObject')),
                ('cartridgeType', models.CharField(max_length=50)),
                ('printerCount', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
            ],
            bases=('inventory.commonobject',),
        ),
    ]
