# Generated by Django 2.1.5 on 2020-08-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_printercartridges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonobject',
            name='dateLastModified',
            field=models.CharField(default='1581370547000', max_length=50, verbose_name='Date Last Modified'),
        ),
    ]
