# Generated by Django 2.1.5 on 2020-08-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20200827_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonId', models.IntegerField()),
            ],
        ),
    ]
