# Generated by Django 2.1.5 on 2020-08-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_recentobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentobject',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
